### PR TITLE
Add june scores

### PR DESCRIPTION
**Pull request by eeeschwartz**
Yelp reached out recently so here's hoping these get pulled into their app

### CODE REVIEW

**Comment by chaserx** [comment]
+1

**Comment by mildmojo** [comment]
:+1:

Y'know, browsing the businesses.csv diff is kind of a cool way of finding out about food places that have opened/closed.

**Comment by eeeschwartz** [comment]
@mildmojo dare I say microsite idea?!?

**Comment by mildmojo** [comment]
@eeeschwartz I was thinking similar. I bet you could do it either as a static site or as a front-end app that hits the GitHub API for commit history & diffs on `businesses.csv`.

**Pull request merged**
